services:
  tsdproxy:
    image: almeidapaulopt/tsdproxy:latest
    container_name: tsdproxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - tsdproxy_data:/data
      - ./config:/config
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - TSNET_FORCE_LOGIN=1
    restart: always
    ports:
      - "8888:8080"
    networks:
      - gti
    labels:
      - tsdproxy.enable=true
      - tsdproxy.name=tsproxy-gti
volumes:
  tsdproxy_data:
networks:
  gti:
    external: true
