- Self-Hosted:
  - Pihole:
      href: https://pihole.porcupine-coho.ts.net/admin
      ping: https://pihole.porcupine-coho.ts.net/admin
      description: "Pihole is a network-wide ad blocker. It blocks ads on all devices connected to your network."
      widget:
        type: pihole
        url: https://pihole.porcupine-coho.ts.net
        key: nermal
  - Coder:
      href: https://coder.porcupine-coho.ts.net
      ping: https://coder.porcupine-coho.ts.net
      description: "Coder is a web-based development environment for writing code. It's a self-hosted alternative to VS Code."
      server: gtr
      container: coder
