services:
  opengist:
    image: ghcr.io/thomiceli/opengist:1
    container_name: opengist
    restart: always
    userns: host
    privileged: true
    user: opengist
    ports:
      - "6157:6157"
    volumes:
      - type: bind
        source: $SERVER_DATA_LOCATION/opengist
        target: /opengist
        consistency: cached
    environment:
      - OG_SSH_GIT_ENABLED=false
      - OG_EXTERNAL_URL=${OPENGIST_EXTERNAL_URL:-?fail}
      - USER=opengist
    networks:
      - mini
    healthcheck:
      test: ["CMD", "curl", "-f", "http://opengist:6157/healthcheck"]
      interval: 1m30s
      timeout: 10s
      retries: 3
networks:
  mini:
    external: true
