services:
  tsdproxy:
    image: almeidapaulopt/tsdproxy:latest
    container_name: tsdproxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - tsdproxy_data:/data
      - ./config:/config
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    restart: always
    ports:
      - "8888:8080"
    networks:
      - gtr
    labels:
      - tsdproxy.enable=true
      - tsdproxy.name=tsproxy-gtr
networks:
  gtr:
    external: true
volumes:
  tsdproxy_data:
