server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://msi.home:3100/loki/api/v1/push

scrape_configs:
- job_name: system
  static_configs:
  - job_name: msi
    static_configs:
    - targets:
        - localhost
      labels:
        job: varlogs
        __path__: /var/log/*log
  - job_name: gti
    static_configs:
    - targets:
        - gti.home
      labels:
        job: varlogs
        __path__: /var/log/*log
  - job_name: gtr
    static_configs:
    - targets:
        - gtr.home
      labels:
        job: varlogs
        __path__: /var/log/*log
  - job_name: mini
    static_configs:
    - targets:
        - mini.home
      labels:
        job: varlogs
        __path__: /var/log/*log
