services:
  komposeui:
    image: jadcham/komposeui
    container_name: komposeui
    restart: always
    ports:
      - "8000:8000"
    labels:
      - tsdproxy.enable=true
      - tsdproxy.name=kompose
    networks:
      - mini
networks:
  mini:
    external: true
