services:
  komposeui:
    image: jadcham/komposeui
    container_name: komposeui
    restart: always
    ports:
      - "8000:8000"
    labels:
      - tsdproxy.enable=true
      - tsdproxy.name=kompose
    networks:
      - mini
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
networks:
  mini:
    external: true
