services:
  memos:
    image: neosmemo/memos:stable
    container_name: memos
    restart: always
    volumes:
      - $SERVER_DATA_LOCATION/memos:/var/opt/memos
    ports:
      - 5230:5230
    networks:
      - mini
networks:
  mini:
    external: true
