services:
  socat:
    image: alpine/socat
    container_name: socat
    restart: always
    command: TCP-LISTEN:6443,fork TCP:docker-desktop:6443
    networks:
      - mini
    ports:
      - 6444:6443
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "6443"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
networks:
  mini:
    external: true
