version: "0.5"

processes:
  Bolt:
    command: "cd bolt.diy && pnpm dev"
    is_daemon: true
    environment:
      - "LMSTUDIO_API_BASE_URL=http://192.168.88.245:1234"
    log_location: "./logs/bolt.log"

  Caddy:
    command: "docker run --rm --name bolt-ai-caddy -p 5544:80 -v $(pwd)/Caddyfile:/etc/caddy/Caddyfile --add-host=host.docker.internal:host-gateway caddy:latest"
    is_daemon: true
    shutdown:
      command: "docker stop bolt-ai-caddy"
      timeout_seconds: 5
    availability:
      restart: always
    depends_on:
      Bolt:
        condition: process_started
    log_location: "./logs/caddy.log"

