services:
  loki:
    image: grafana/loki:latest
    container_name: loki
    restart: always
    volumes:
      - ./config/loki-config.yaml:/mnt/config/loki-config.yaml
      - loki_data:/tmp
    ports:
      - "3100:3100"
    command: "-config.file=/mnt/config/loki-config.yaml"
    networks:
      - msi
    healthcheck:
      test: ["CMD-SHELL", "wget --spider --quiet http://localhost:3100/ready || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
volumes:
  loki_data:
networks:
  msi:
    external: true
