networks:
  rhms:
    external: true
  cursorlens:
    external: false
services:
  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - cursorlens

  app:
    build:
      context: cursorlens
      dockerfile: Dockerfile
    ports:
      - "33000:3000"
    environment:
      DATABASE_URL: ${CURSORLENS_DATABASE_URL?fail}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - cursorlens
      - rhms

volumes:
  postgres_data:
