services:
  navidrome:
    image: deluan/navidrome:latest
    user: $PUID:$PGID
    ports:
      - "4533:4533"
    restart: unless-stopped
    environment:
      # Optional: put your config options customization here. Examples:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: ""
      ND_ENABLEINSIGHTSCOLLECTOR: "false"
      ND_TRACKING_ENABLED: "false" # Added tracking option
    volumes:
      - $SERVER_DATA_LOCATION/navidrome/data:/data
      - $NAVIDROME_MUSIC_DIR:/music:ro
networks:
  mini:
    external: true
