services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: always
    volumes:
      - open-webui-data:/app/backend/data
    ports:
      - 8686:8080
    networks:
      - gti
      - webui
    environment:
      - OLLAMA_BASE_URL=${GTI_OLLAMA_BASE_URL?fail}
      - WEBUI_SECRET_KEY=${OPENWEBUI_API_KEY?fail}
      - ENABLE_CODE_INTERPRETER=${ENABLE_CODE_INTERPRETER?fail}
      - CODE_EXECUTION_ENGINE=${CODE_EXECUTION_ENGINE?fail}
      - CODE_EXECUTION_JUPYTER_URL=${CODE_EXECUTION_JUPYTER_URL?fail}
      - CODE_EXECUTION_JUPYTER_AUTH=${CODE_EXECUTION_JUPYTER_AUTH?fail}
      - CODE_EXECUTION_JUPYTER_TOKEN=${CODE_EXECUTION_JUPYTER_TOKEN?fail}
      - CODE_EXECUTION_JUPYTER_TIMEOUT=${CODE_EXECUTION_JUPYTER_TIMEOUT?fail}
      - CODE_INTERPRETER_ENGINE=${CODE_INTERPRETER_ENGINE?fail}
      - CODE_INTERPRETER_JUPYTER_URL=${CODE_INTERPRETER_JUPYTER_URL?fail}
      - CODE_INTERPRETER_JUPYTER_AUTH=${CODE_INTERPRETER_JUPYTER_AUTH?fail}
      - CODE_INTERPRETER_JUPYTER_TOKEN=${CODE_INTERPRETER_JUPYTER_TOKEN?fail}
      - CODE_INTERPRETER_JUPYTER_TIMEOUT=${CODE_INTERPRETER_JUPYTER_TIMEOUT?fail}

  webui-searxng-redis:
    container_name: webui-searxng-redis
    image: docker.io/valkey/valkey:8-alpine
    command: valkey-server --save 30 1 --loglevel warning
    restart: unless-stopped
    networks:
      - webui
    volumes:
      - valkey-data2:/data
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  webui-searxng:
    container_name: webui-searxng
    image: docker.io/searxng/searxng:latest
    restart: unless-stopped
    networks:
      - webui
    volumes:
      - ./searxng:/etc/searxng:rw
    environment:
      - SEARXNG_HOSTNAME=webui-searxng:8080
      - SEARXNG_BASE_URL=http://webui-searxng:8080
      - SEARXNG_REDIS_URL=redis://webui-searxng-redis:6379
      - UWSGI_WORKERS=4
      - UWSGI_THREADS=4
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  jupyter:
    image: jupyter/minimal-notebook:latest
    container_name: jupyter-notebook
    ports:
    - "18888:8888"
    volumes:
    - jupyter_data:/home/jovyan/work
    environment:
    - JUPYTER_ENABLE_LAB=yes
    - JUPYTER_TOKEN=123456
    networks:
      - webui
      - gti
    labels:
      - tsdproxy.enable=true
      - tsdproxy.name=jupyter

volumes:
  open-webui-data:
  valkey-data2:
  jupyter_data:

networks:
  gti:
    external: true
  webui:
    external: false

