services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
    volumes:
      - grafana_storage:/var/lib/grafana
    networks:
      - msi
volumes:
  grafana_storage:
networks:
  msi:
    external: true
