services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD?Missing GF_SECURITY_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_DOMAIN=grafana.rhcloud.dev
      - GF_SMTP_ENABLED=false
    ports:
      - 3000:3000
    volumes:
      - grafana_storage:/var/lib/grafana
    networks:
      - msi
    healthcheck:
      test: ["CMD-SHELL", "wget --spider --quiet http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
volumes:
  grafana_storage:
networks:
  msi:
    external: true
