services:
  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    restart: always
    volumes:
      - ./config/promtail-config.yaml:/mnt/config/promtail-config.yaml
      - /var/log:/var/log
    command: "-config.file=/mnt/config/promtail-config.yaml"
    networks:
      - gti
    healthcheck:
      test: ["CMD-SHELL", "wget --spider --quiet http://localhost:9080/ready || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
networks:
  gti:
    external: true
