- name: Home
  # Optionally, if you only have a single page you can hide the desktop navigation for a cleaner look
  hide-desktop-navigation: true
  columns:
    - size: small
      widgets:
        - type: search
          search-engine: google
          bangs:
            - title: searxng
              shortcut: "!x"
              url: https://search.porcupine-coho.ts.net/search?q={QUERY}
            - title: YouTube
              shortcut: "!yt"
              url: https://www.youtube.com/results?search_query={QUERY}
        - type: calendar
          first-day-of-week: sunday
        - type: clock
          hour-format: 12h
          timezones:
            - timezone: Asia/Taipei
              label: Taipei
            - timezone: America/Chicago
              label: Austin
            - timezone: Europe/London
              label: London
            - timezone: Europe/Berlin
              label: Berlin
        - type: rss
          limit: 10
          collapse-after: 3
          cache: 12h
          feeds:
            - url: https://selfh.st/rss/
              title: selfh.st
            - url: https://ciechanow.ski/atom.xml
            - url: https://www.joshwcomeau.com/rss.xml
              title: Josh Comeau
            - url: https://samwho.dev/rss.xml
            - url: https://ishadeed.com/feed.xml
              title: Ahmad Shadeed
    - size: full
      widgets:
        - type: group
          widgets:
            - type: reddit
              subreddit: news
              show-thumbnails: true
            - type: hacker-news
              limit: 50
              collapse-after: 5
            - type: lobsters
              limit: 50
              collapse-after: 5
              sort-by: hot
            - type: reddit
              subreddit: minimalism
              show-thumbnails: true
            - type: reddit
              subreddit: onebag
              show-thumbnails: true
            - type: reddit
              subreddit: usefulscripts
              show-thumbnails: true
            - type: reddit
              subreddit: ansible
              show-thumbnails: true
        - type: videos
          channels:
            - UCmaqnBHJZB2UI-i07mmz0kw # Tulok and Mango
            - UCwWhs_6x42TyRM4Wstoq8HA # The Daily Show
            - UC3XTzVzaHQEd30rQbuvCtTQ # Last Week Tonight
            - UCy6kyFxaMqGtpE3pQTflK8A # Real Time with Bill Maher
        - type: group
          widgets:
            - type: reddit
              subreddit: technology
              show-thumbnails: true
            - type: reddit
              subreddit: selfhosted
              show-thumbnails: true
            - type: reddit
              subreddit: golang
              show-thumbnails: true
            - type: reddit
              subreddit: ollama
              show-thumbnails: true
            - type: reddit
              subreddit: mcp
              show-thumbnails: true
            - type: reddit
              subreddit: ChatGPTCoding
              show-thumbnails: true
    - size: small
      widgets:
        - type: weather
          location: New York, New York, United States
          units: imperial
          hour-format: 12h
        - type: bookmarks
          groups:
            - title: rhcloud
              color: 10 70 50
              links:
                - title: ai.rhcloud.dev
                  url: https://ai.rhcloud.dev
                - title: git.rhcloud.dev
                  url: https://git.rhcloud.dev
                - title: gist.rhcloud.dev
                  url: https://gist.rhcloud.dev
                - title: docmost.rhcloud.dev
                  url: https://docmost.rhcloud.dev
                - title: tools.rhcloud.dev
                  url: https://tools.rhcloud.dev
                - title: hoarder.rhcloud.dev
                  url: https://hoarder.rhcloud.dev
                - title: photos.rhcloud.dev
                  url: https://photos.rhcloud.dev
                - title: mermaid.rhcloud.dev
                  url: https://mermaid.rhcloud.dev
                - title: music.rhcloud.dev
                  url: https://music.rhcloud.dev
            - title: ts
              color: 200 50 50
              links:
                - title: pihole
                  url: http://pihole.home/admin/index.php
                - title: search
                  url: http://search.porcupine-coho.ts.net
                - title: kompose
                  url: https://kompose.porcupine-coho.ts.net
                - title: fs
                  url: https://fs.porcupine-coho.ts.net
