services:
  it-tools:
    image: 'corentinth/it-tools:latest'
    container_name: tools
    ports:
      - '8126:80'
    restart: always
    networks:
      - gti
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
networks:
  gti:
    external: true
