services:
  searxng:
    image: docker.io/searxng/searxng:latest
    container_name: perplexica-searxng
    volumes:
      - ./Perplexica/searxng:/etc/searxng:rw
    ports:
      - 4000:8080
    networks:
      - perplexica-network
    restart: unless-stopped

  app:
    image: itzcrazykns1337/perplexica:main
    container_name: perplexica-app
    build:
      context: Perplexica
      dockerfile: app.dockerfile
    environment:
      - SEARXNG_API_URL=http://perplexica-searxng:8080
    ports:
      - 3000:3000
    networks:
      - perplexica-network
    labels:
      - tsdproxy.enable=true
      - tsdproxy.name=perplexica
    volumes:
      - backend-dbstore:/home/perplexica/data
      - uploads:/home/perplexica/uploads
      - ./config.toml:/home/perplexica/config.toml
    restart: unless-stopped

networks:
  perplexica-network:

volumes:
  backend-dbstore:
  uploads:
