version: "3.8"

services:
  gitea:
    image: gitea/gitea:latest
    environment:
      APP_NAME: gitea
      USER_UID: 1000
      USER_GID: 1000
      USER: git
      RUN_MODE: prod
      DOMAIN: ${GITEA_DOMAIN:?Variable GITEA_DOMAIN not set}
      HTTP_PORT: 3000
      ROOT_URL: ${GITEA_ROOT_URL:?Variable GITEA_ROOT_URL not set}
      DB_TYPE: sqlite3
      GITEA__server__LFS_JWT_SECRET: ${GITEA_LFS_JWT_SECRET:?Variable GITEA_LFS_JWT_SECRET not set}
      GIT_SSL_NO_VERIFY: true
      GITEA__security__INTERNAL_TOKEN: ${GITEA_INTERNAL_TOKEN:?Variable GITEA_INTERNAL_TOKEN not set}
      GITEA__oauth2__JWT_SECRET: ${GITEA_JWT_SECRET:?Variable GITEA_JWT_SECRET not set}
      GITEA__security__SECRET_KEY: ${GITEA_SECRET_KEY:?Variable GITEA_SECRET_KEY not set}
    volumes:
      - ${SERVER_DATA_LOCATION:?Variable SERVER_DATA_LOCATION is not set}/gitea:/data
      - ${HOME}/.local/gitea/app.ini:/data/gitea/conf/app.ini
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - target: 3000
        published: 3001
        mode: host
