networks:
  movies:
    external: false
  mini:
    external: true

services:
  emby:
    image: emby/embyserver:latest
    ports:
      - target: 8096 # http
        published: 8096
        mode: host
      - target: 8920 # https
        published: 8920
        mode: host
    networks:
      - movies
      - mini
    environment:
      - UID=${PUID?fail}
      - GID=${PGID?FAIL}
      - GIDLIST=${PUID?FAIL}
    volumes:
      - ${SERVER_DATA_LOCATION?fail}/emby:/config
      - ${EMBY_MOVIE_PATH?fail}:/mnt/share1
      - ${EMBY_DOWNLOAD_MOVIE_PATH?fail}:/mnt/share2
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
