services:
  marimo:
    build: .
    image: marimo:latest
    container_name: marimo
    restart: always
    init: true
    ports:
      - "8080:8080"
    volumes:
      - marimo_data:/app
    labels:
      - tsdproxy.enable=true
      - tsdproxy.name=marimo
      - homepage.group=gtr
      - homepage.name=marimo
      - homepage.instance.public.href=https://marimo.porcupine-coho.ts.net
      - homepage.instance.public.ping=https://marimo.porcupine-coho.ts.net
      - homepage.description=Marimo is a better jupyter notebook.
    networks:
      - gtr
volumes:
  marimo_data:
networks:
  gtr:
    external: true
