services:
  marimo:
    build: .
    image: marimo:latest
    container_name: marimo
    restart: always
    init: true
    ports:
      - "7777:8080"
    volumes:
      - marimo_data:/app
    labels:
      - tsdproxy.enable=true
      - tsdproxy.name=marimo
    networks:
      - gtr
    healthcheck:
      test: ["CMD", "curl", "-f", "http://marimo:8080/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
volumes:
  marimo_data:
networks:
  gtr:
    external: true
