---
- name: Create and configure VM
  hosts: gtr
  vars:
    vmid: 9000
    proxmox_user_password: "{{ lookup('env', 'PROXMOX_USER_PASSWORD') }}"
    ubuntu_version: noble
    disk_image: noble-server-cloudimg-amd64.img
    images_path: /root/cloud-images
  tasks:
    - block:
      - name: Ensure cloud images directory
        file:
          path: "{{ images_path }}"
          state: directory
      - name: Check if ubuntu cloud image exists
        stat:
          path: "{{ images_path }}/{{ disk_image }}"
        register: disk_image_stat
      - name: Calculate age of the file in days
        set_fact:
          file_age: "{{ ((ansible_date_time.epoch | int) - (disk_image_stat.stat.mtime | int)) / 60 / 60 / 24 }}"
        when: disk_image_stat.stat.exists
      - name: Register if file is older than 7 days
        set_fact:
          file_is_old: "{{ file_age > 7 }}"
        when: disk_image_stat.stat.exists
      - block:
        - name: Download ubuntu cloud image if it does not exist
          get_url:
            url: https://cloud-images.ubuntu.com/{{ ubuntu_version }}/current/{{ disk_image }}
            dest: "{{ images_path }}/{{ disk_image }}"
        - name: Check if virt-customize is installed
          command: which virt-customize
          register: virt_customize_installed
          changed_when: false
        - name: Install libguestfs-tools
          apt:
            name: libguestfs-tools
            state: present
          when: virt_customize_installed.rc != 0
        - name: Inject apt packages into cloud image
          command: >
            virt-customize -a {{ images_path }}/{{ disk_image }} \
              --install qemu-guest-agent,zsh,curl,vim,direnv \
              --run-command 'curl -fsSL https://get.docker.com | sh' \
              --run-command 'curl -fsSL https://tailscale.com/install.sh | sh' \
              --run-command 'curl -fsSL https://get.jetify.com/devbox | bash' \
              --run-command 'chsh -s /bin/zsh root' \
              --run-command 'sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"'
        when: disk_image_stat.stat.exists == False or file_is_old
      - name: Copy authorized keys to temp file on remote
        copy:
          content: "{{ lookup('env', 'PROXMOX_USER_PUBLIC_KEY') }}"
          dest: /tmp/authorized_keys
    - name: Create VM
      command:
        cmd: >
          qm create {{ vmid }} \
            --name "noble-server" \
            --memory 2048 \
            --balloon 0 \
            --net0 virtio,bridge=vmbr0 \
            --cores 2 \
            --sockets 2 \
            --cpu cputype=host \
            --net0 virtio,bridge=vmbr0,firewall=1 \
            --serial0 socket \
            --vga serial0 \
            --agent enabled=1 \
            --ciuser rh \
            --cipassword {{ proxmox_user_password }} \
            --sshkeys /tmp/authorized_keys \
            --ipconfig0 ip=dhcp,ip6=dhcp

    - name: Import disk
      command: qm importdisk {{ vmid }} {{ disk_image }} local-lvm

    - name: Attach disk
      command: qm set {{ vmid }} --scsihw virtio-scsi-pci --scsi0 local-lvm:vm-{{ vmid }}-disk-0,size=32G,ssd=1

    - name: Set boot disk
      command: qm set {{ vmid }} --boot c --bootdisk scsi0

    - name: Set cloud-init
      command: qm set {{ vmid }} --ide2 local-lvm:cloudinit

    - name: Set autostart on vm before converting to template
      command: qm set {{ vmid }} --autostart 1

    - name: Convert to template
      command: qm template {{ vmid }}
