name: azuracast
services:
    web:
        container_name: azuracast
        image: 'ghcr.io/azuracast/azuracast:${AZURACAST_VERSION:-latest}'
        labels:
            - com.centurylinklabs.watchtower.scope=azuracast
            - com.centurylinklabs.watchtower.enable=true
        ports:
            - '${AZURACAST_HTTP_PORT:-80}:${AZURACAST_HTTP_PORT:-80}'
            - '${AZURACAST_SFTP_PORT:-2022}:${AZURACAST_SFTP_PORT:-2022}'
        env_file:
            - azuracast.env
            - .env
        volumes:
            - 'station_data:/var/azuracast/stations'
            - 'backups:/var/azuracast/backups'
            - 'db_data:/var/lib/mysql'
            - 'www_uploads:/var/azuracast/storage/uploads'
            - 'shoutcast2_install:/var/azuracast/storage/shoutcast2'
            - 'stereo_tool_install:/var/azuracast/storage/stereo_tool'
            - 'rsas_install:/var/azuracast/storage/rsas'
            - 'geolite_install:/var/azuracast/storage/geoip'
            - 'sftpgo_data:/var/azuracast/storage/sftpgo'
            - 'acme:/var/azuracast/storage/acme'
        restart: unless-stopped
        ulimits:
            nofile:
                soft: 65536
                hard: 65536
        logging:
            options:
                max-size: 1m
                max-file: '5'
    updater:
        container_name: azuracast_updater
        image: 'ghcr.io/azuracast/updater:latest'
        restart: unless-stopped
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
        logging:
            options:
                max-size: 1m
                max-file: '5'
volumes:
    db_data: {  }
    acme: {  }
    shoutcast2_install: {  }
    stereo_tool_install: {  }
    rsas_install: {  }
    geolite_install: {  }
    sftpgo_data: {  }
    station_data: {  }
    www_uploads: {  }
    backups: {  }
