services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    restart: always
    ports:
      - "3010:3001"
    volumes:
      - uptime-kuma:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - tsdproxy.enable=true
      - tsdproxy.name=uptime-kuma-msi
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3001 || exit 1"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
volumes:
  uptime-kuma:
networks:
  msi:
    external: true
