services:
  glance:
    container_name: glance
    image: glanceapp/glance
    volumes:
      - ./config:/app/config
      - ./assets:/app/assets
    environment:
      - MY_SECRET_TOKEN=${GLANCE_SECRET_TOKEN?fail}
    ports:
      - 8080:8080
    networks:
      - mini
    restart: unless-stopped
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    labels:
      - tsdproxy.enable=true
      - tsdproxy.name=glance
      - com.centurylinklabs.watchtower.enable=true
networks:
  mini:
    external: true
