services:
  vpn:
    container_name: vpn
    # image: ghcr.io/bubuntux/nordvpn:latest
    build:
      context: nordvpn
    cap_add:
      - NET_ADMIN
      - NET_RAW
    restart: unless-stopped
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    devices:
      - /dev/net/tun
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - mini
    environment:
      - PUID=${BT_PUID?fail}
      - PGID=${BT_PGID?fail}
      - TOKEN=${VPN_TOKEN?fail}
      - CONNECT=${VPN_COUNTRY?fail}
      - TECHNOLOGY=NordLynx
      - NETWORK=${VPN_NETWORK?fail}
      - CYBER_SEC=enable
      - FIREWALL=disable
      - PROTOCOL=UDP
      - CATEGORY=P2P
      - DNS=1.1.1.1,8.8.8.8
      - OPENVPN_OPTS=--pull-filter ignore "ping-restart" --ping-exit 120
      - TZ='America/New_York'
    ports:
      - 9091:9091 # Transmission web UI
      - 51413:51413 # Transmission bittorrent daemon
      - 51413:51413/udp # Transmission bittorrent daemon

  transmission:
    image: ghcr.io/linuxserver/transmission:latest
    container_name: transmission
    restart: unless-stopped
    network_mode: service:vpn # run on the vpn network
    environment:
      - PUID=${BT_PUID?fail}
      - PGID=${BT_PGID?fail}
      - TZ='America/New_York'
    volumes:
      - $SERVER_DATA_LOCATION/transmission/downloads/:/downloads
      - $SERVER_DATA_LOCATION/transmission/config:/config
      - $SERVER_DATA_LOCATION/transmission/watch:/watch

networks:
  mini:
    external: true
