services:
  web:
    image: ghcr.io/karakeep-app/karakeep:${KARAKEEP_VERSION:-release}
    container_name: kerakeep
    restart: always
    volumes:
      - $SERVER_DATA_LOCATION/kerakeep/data:/data
    ports:
     - 13000:3000
    environment:
      MEILI_ADDR: http://meilisearch:7700
      BROWSER_WEB_URL: http://chrome:9222
      MEILI_MASTER_KEY: ${KERAKEEP_MEILI_MASTER_KEY?Variable not set}
      NEXTAUTH_URL: ${KERAKEEP_NEXTAUTH_URL?Variable not set}
      NEXTAUTH_SECRET: ${KERAKEEP_NEXTAUTH_SECRET?Variable not set}
      DATA_DIR: /data
      DISABLE_SIGNUPS: "true"
      OLLAMA_BASE_URL: ${GTI_OLLAMA_BASE_URL?fail}
      INFERENCE_TEXT_MODEL: ${GTI_INFERENCE_TEXT_MODEL?fail}
      INFERENCE_IMAGE_MODEL: ${GTI_INFERENCE_IMAGE_MODEL?fail}
      EMBEDDING_TEXT_MODEL: ${GTI_EMBEDDING_TEXT_MODEL?fail}
    networks:
      - mini
      - kerakeep
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  chrome:
    image: gcr.io/zenika-hub/alpine-chrome:123
    container_name: chrome
    restart: always
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
    networks:
      - kerakeep
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  meilisearch:
    image: getmeili/meilisearch:v1.11.1
    container_name: meilisearch
    restart: always
    environment:
      MEILI_MASTER_KEY: ${KERAKEEP_MEILI_MASTER_KEY?Variable not set}
      MEILI_NO_ANALYTICS: "true"
    volumes:
      - $SERVER_DATA_LOCATION/kerakeep/meilisearch:/meili_data
    networks:
      - kerakeep
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

networks:
  mini:
    external: true
  kerakeep:
    external: false
