services:
  memos:
    image: neosmemo/memos:stable
    container_name: workmemos
    restart: always
    volumes:
      - $SERVER_DATA_LOCATION/workmemos:/var/opt/memos
    ports:
      - 5231:5230
    networks:
      - mini
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5230"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
networks:
  mini:
    external: true
