services:
  searxng:
    image: docker.io/searxng/searxng:latest
    container_name: perplexica-searxng
    volumes:
      - $SERVER_DATA_LOCATION/perplexica/searxng:/etc/searxng:rw
    # ports:
    #   - 4000:8080
    networks:
      - perplexica-network
    restart: unless-stopped

  perplexica-backend:
    build:
      context: ./Perplexica
      dockerfile: backend.dockerfile
    image: itzcrazykns1337/perplexica-backend:main
    environment:
      - SEARXNG_API_URL=http://searxng:8080
    depends_on:
      - searxng
    ports:
      - 13031:3001
    volumes:
      - $SERVER_DATA_LOCATION/perplexica/backend-dbstore:/home/perplexica/data
      - $SERVER_DATA_LOCATION/perplexica/uploads:/home/perplexica/uploads
      - ./config.toml:/home/perplexica/config.toml
    # extra_hosts:
    #   - 'host.docker.internal:host-gateway'
    networks:
      - mini
      - perplexica-network
    restart: unless-stopped

  perplexica-frontend:
    build:
      context: ./Perplexica
      dockerfile: app.dockerfile
      args:
        - NEXT_PUBLIC_API_URL=http://127.0.0.1:13031/api
        - NEXT_PUBLIC_WS_URL=ws://127.0.0.1:13031
    image: itzcrazykns1337/perplexica-frontend:main
    depends_on:
      - perplexica-backend
    ports:
      - 13030:3000
    networks:
      - mini
      - perplexica-network
    restart: unless-stopped

networks:
  perplexica-network:
    external: false
  mini:
    external: true
