services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always
    command:
      - --cleanup=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - rhms
networks:
  rhms:
    external: true
