services:
  tsdproxy:
    image: almeidapaulopt/tsdproxy:latest
    container_name: tsdproxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
      - ./config:/config
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    restart: unless-stopped
    ports:
      - "8888:8080"
    networks:
      - mini
    labels:
      - tsdproxy.enable=true
      - tsdproxy.name=minitsproxy
networks:
  mini:
    external: true
