services:
  tsdproxy:
    image: almeidapaulopt/tsdproxy:latest
    container_name: tsdproxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $SERVER_DATA_LOCATION/tsdproxy:/data
      - ./config:/config
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    restart: always
    ports:
      - "8888:8080"
    networks:
      - mini
networks:
  mini:
    external: true
