services:
  caddy:
    image: caddy:2.7-alpine
    container_name: lmstudio-proxy
    ports:
      - "11234:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    environment:
      - API_KEY=${LMSTUDIO_API_KEY}
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Required for Linux compatibility
    networks:
      - rhms

networks:
  rhms:
    external: true

