services:
  docmost:
    image: docmost/docmost:latest
    container_name: docmost
    depends_on:
      - db
      - redis
    networks:
      - docmost
      - mini
    environment:
      APP_URL: ${DOCMOST_APP_URL?fail}
      APP_SECRET: ${DOCMOST_APP_SECRET?fail}
      DATABASE_URL: ${DOCMOST_DATABASE_URL?fail}
      REDIS_URL: "redis://redis:6379"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - "3989:3000"
    restart: always
    volumes:
      - $SERVER_DATA_LOCATION/docmost/storage:/app/data/storage

  db:
    image: postgres:16-alpine
    container_name: docmost-db
    networks:
      - docmost
    environment:
      POSTGRES_DB: ${DOCMOST_POSTGRES_DB?fail}
      POSTGRES_USER: ${DOCMOST_POSTGRES_USER?fail}
      POSTGRES_PASSWORD: ${DOCMOST_POSTGRES_PASSWORD?fail}
    restart: always
    volumes:
      - $SERVER_DATA_LOCATION/docmost/postgres:/var/lib/postgresql/data
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  redis:
    image: redis:7.2-alpine
    container_name: docmost-redis
    restart: unless-stopped
    networks:
      - docmost
    volumes:
      - $SERVER_DATA_LOCATION/docmost/redis:/data
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

networks:
  mini:
    external: true
  docmost:
    external: false
