services:
  web:
    image: ghcr.io/hoarder-app/hoarder:${HOARDER_VERSION?fail}
    container_name: hoarder
    restart: always
    volumes:
      - $SERVER_DATA_LOCATION/hoarder/data:/data
    ports:
     - 13000:3000
    environment:
      MEILI_ADDR: http://meilisearch:7700
      BROWSER_WEB_URL: http://chrome:9222
      MEILI_MASTER_KEY: ${HOARDER_MEILI_MASTER_KEY?Variable not set}
      NEXTAUTH_URL: ${HOARDER_NEXTAUTH_URL?Variable not set}
      NEXTAUTH_SECRET: ${HOARDER_NEXTAUTH_SECRET?Variable not set}
      DATA_DIR: /data
      DISABLE_SIGNUPS: "true"
      OLLAMA_BASE_URL: "https://rhms.home:11434"
      INFERENCE_TEXT_MODEL: "qwen2.5:32b"
      INFERENCE_IMAGE_MODEL: "llama3.2-vision:90b"
    networks:
      - mini
      - hoarder
  chrome:
    image: gcr.io/zenika-hub/alpine-chrome:123
    container_name: chrome
    restart: always
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
    networks:
      - hoarder
  meilisearch:
    image: getmeili/meilisearch:v1.11.1
    container_name: meilisearch
    restart: always
    expose:
      - 7700
    environment:
      MEILI_MASTER_KEY: ${HOARDER_MEILI_MASTER_KEY?Variable not set}
      MEILI_NO_ANALYTICS: "true"
    volumes:
      - $SERVER_DATA_LOCATION/hoarder/meilisearch:/meili_data
    networks:
      - hoarder

networks:
  mini:
    external: true
  hoarder:
    external: false
