services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    environment:
      TZ: 'America/New_York'
      PIHOLE_DNS_: ${PIHOLE_DNS:-?fail}
      DNSSEC: 'false'
      VIRTUAL_HOST: 'pihole'
      WEBTHEME: 'default-dark'
      SKIPGRAVITYONBOOT: 'true'
      WEBPASSWORD: ${PIHOLE_WEBPASSWORD:-?fail}
      DNSMASQ_LISTENING: 'all'
    volumes:
      - ./pihole/etc-pihole:/etc/pihole
      - ./pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/
    cap_add:
      - NET_ADMIN
    depends_on:
      - pihole-tailscale
    network_mode: service:pihole-tailscale
    restart: unless-stopped
  pihole-tailscale:
    image: tailscale/tailscale:latest
    container_name: pihole-tailscale
    hostname: pihole
    environment:
      TS_AUTHKEY: ${PIHOLE_TS_AUTHKEY:-?fail}
      TS_STATE_DIR: /var/lib/tailscale
      TS_USERSPACE: false
      TS_HOSTNAME: pihole
    volumes:
      - ./tailscale:/var/lib/tailscale
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    restart: unless-stopped
