services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    networks:
      - msi
    labels:
      - tsdproxy.enable=true
      - tsdproxy.name=prometheus
    healthcheck:
      test: ["CMD-SHELL", "wget --spider --quiet http://localhost:9090/-/healthy || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
volumes:
  prometheus_data:
networks:
  msi:
    external: true
