services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    networks:
      - msi
      - prometheus
    labels:
      - tsdproxy.enable=true
      - tsdproxy.name=prometheus
    healthcheck:
      test: ["CMD-SHELL", "wget --spider --quiet http://localhost:9090/-/healthy || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    restart: always
    expose:
      - 9100
    healthcheck:
      test: ["CMD-SHELL", "wget --spider --quiet http://localhost:9100/metrics || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    container_name: cadvisor
    restart: always
    ports:
      - 8181:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - msi
      - prometheus
    labels:
      - tsdproxy.enable=true
      - tsdproxy.name=cadvisor
volumes:
  prometheus_data:
networks:
  msi:
    external: true
  prometheus:
    external: false
