global:
  scrape_interval: 120s
  scrape_timeout: 120s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
    api_version: v2
scrape_configs:
- job_name: 'prometheus'
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets: ['localhost:9090','cadvisor:8080','node-exporter:9100']
- job_name: msi
  static_configs:
  - targets: ['msi.home:9100']
- job_name: gtr
  static_configs:
  - targets: ['gtr.home:9100']
- job_name: mini
  static_configs:
  - targets: ['mini.home:9100']
- job_name: rhms
  static_configs:
  - targets: ['rhms.home:9100']
- job_name: gti
  static_configs:
  - targets: ['gti.home:9100']
- job_name: rm1
  static_configs:
  - targets: ['rm1.home:9100']
- job_name: rm2
  static_configs:
  - targets: ['rm2.home:9100']
- job_name: rm4
  static_configs:
  - targets: ['rm4.home:9100']
